---

version: "3"

services:
  reverse_proxy:
    image: "jwilder/nginx-proxy:latest"
    container_name: "reverse_proxy"
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./dhparam:/etc/nginx/dhparam"
      - "./vhost:/etc/nginx/vhost.d"
      - "./certs:/etc/nginx/certs:ro"
      - "/run/docker.sock:/tmp/docker.sock:ro"
      - "./conf_files:/etc/nginx/conf.d/"
    restart: "always"
    networks:
      - net2
    ports:
      - "80:80"
      - "443:443"

  letsencrypt:
    image: "jrcs/letsencrypt-nginx-proxy-companion:latest"
    container_name: "letsencrypt_helper"
    depends_on:
      - reverse_proxy
    volumes:
      - "./html:/usr/share/nginx/html"
      - "./dhparam:/etc/nginx/dhparam"
      - "./vhost:/etc/nginx/vhost.d"
      - "./certs:/etc/nginx/certs"
      - "/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - NGINX_PROXY_CONTAINER
      - DEFAULT_EMAIL
    restart: "always"
    networks:
      - net2

networks:
  net2:
    external: true
