---

version: "3"

services:
  nc_db:
    image: "mariadb:10.5.9"
    container_name: "nc_db"
    volumes:
      - "./NCMariaDB:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_RANDOW_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    restart: "always"
    networks:
      - common2

  nc:
    image: "nextcloud:28.0.4"
    container_name: "nextcloud"
    depends_on:
      - nc_db
    volumes:
      - "./data:/var/www/html/data"
      - "./config:/var/www/html/config"
      - "./apps:/var/www/html/apps"
      - "./custom_apps:/var/www/html/custom_apps"
    environment:
      - LETSENCRYPT_HOST
      - VIRTUAL_HOST
      - TRUSTED_PROXIES
      - OVERWRITEPROTOCOL
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_HOST
      - NEXTCLOUD_TRUSTED_DOMAINS
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
    restart: "always"
    networks:
      - net2
      - common2

  collabora:
    image: collabora/code
    container_name: "collabora"
    depends_on:
      - nc
    restart: "always"
    environment:
      - aliasgroup
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - "extra_params=--o:ssl.enable=false  --o:ssl.termination=true"
    networks:
      - net2

networks:
  net2:
    external: true
  common2:
    internal: true
