version: "3"
services:
        swagify:
                image: "swagify:stable"
                container_name: "swagify"
                environment:
                        - VIRTUAL_HOST
                        - LETSENCRYPT_HOST
                networks:
                        - net2
                restart: "always"

networks:
        net2:
                external: true
